//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18052
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archiver.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\KaikeiSystem\\publish")]
        public string publishDir {
            get {
                return ((string)(this["publishDir"]));
            }
            set {
                this["publishDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kaikei.db.ver1.original")]
        public string dbFile {
            get {
                return ((string)(this["dbFile"]));
            }
            set {
                this["dbFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbupdate.scr")]
        public string dbUpdateFile {
            get {
                return ((string)(this["dbUpdateFile"]));
            }
            set {
                this["dbUpdateFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>KaikeiSystem.exe</string>
  <string>KaikeiSystemBody.exe</string>
  <string>LicenseClient.exe</string>
  <string>DatabaseUpdater.exe</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection binFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["binFiles"]));
            }
            set {
                this["binFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\KaikeiSystem\\bin\\Release")]
        public string binDir {
            get {
                return ((string)(this["binDir"]));
            }
            set {
                this["binDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kaikei.db")]
        public string dstDbFile {
            get {
                return ((string)(this["dstDbFile"]));
            }
            set {
                this["dstDbFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DatabaseUpdater.exe")]
        public string dbUpdater {
            get {
                return ((string)(this["dbUpdater"]));
            }
            set {
                this["dbUpdater"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KaikeiSystemBody.exe")]
        public string mainBin {
            get {
                return ((string)(this["mainBin"]));
            }
            set {
                this["mainBin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KaikeiSystem_")]
        public string archivePrefix {
            get {
                return ((string)(this["archivePrefix"]));
            }
            set {
                this["archivePrefix"] = value;
            }
        }
    }
}
