//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaikeiSystemBody.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KaikeiSystemBody.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap arrow_right {
            get {
                object obj = ResourceManager.GetObject("arrow_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   すべて に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionAll {
            get {
                return ResourceManager.GetString("CaptionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionConfirm {
            get {
                return ResourceManager.GetString("CaptionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionError {
            get {
                return ResourceManager.GetString("CaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excelに出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionExcelExport {
            get {
                return ResourceManager.GetString("CaptionExcelExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionHierarchy {
            get {
                return ResourceManager.GetString("CaptionHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionHierarchyChukubun {
            get {
                return ResourceManager.GetString("CaptionHierarchyChukubun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   大区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionHierarchyDaikubun {
            get {
                return ResourceManager.GetString("CaptionHierarchyDaikubun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   補助科目 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionHierarchyHojokamoku {
            get {
                return ResourceManager.GetString("CaptionHierarchyHojokamoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   小区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionHierarchySyoukubun {
            get {
                return ResourceManager.GetString("CaptionHierarchySyoukubun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}年度は{1}回数の補正予算が含まれています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionHoseiKaisuu {
            get {
                return ResourceManager.GetString("CaptionHoseiKaisuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   事業活動支出計 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionJigyouShisyutsuKei {
            get {
                return ResourceManager.GetString("CaptionJigyouShisyutsuKei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   事業活動収入計 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionJigyouSyuunyuuKei {
            get {
                return ResourceManager.GetString("CaptionJigyouSyuunyuuKei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   事業活動による収支 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionJigyouSyuushi {
            get {
                return ResourceManager.GetString("CaptionJigyouSyuushi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   事業活動資金収支差額 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionJigyouSyuushiSagaku {
            get {
                return ResourceManager.GetString("CaptionJigyouSyuushiSagaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   経常増減差額 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionKeijouZougenSagaku {
            get {
                return ResourceManager.GetString("CaptionKeijouZougenSagaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   基本財産（有形固定資産） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionKihonZaisanYuukei {
            get {
                return ResourceManager.GetString("CaptionKihonZaisanYuukei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}
        ///{1}
        ///ver.{2} (db ver.{3}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionMenuFormInfo {
            get {
                return ResourceManager.GetString("CaptionMenuFormInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (新規) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionNewRowId {
            get {
                return ResourceManager.GetString("CaptionNewRowId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}年度は補正予算をくんでいません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionNoHoseiYosan {
            get {
                return ResourceManager.GetString("CaptionNoHoseiYosan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サービス活動外費用計 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionServiceKatsudouGaiHiyouKei {
            get {
                return ResourceManager.GetString("CaptionServiceKatsudouGaiHiyouKei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サービス活動外収益計 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionServiceKatsudouGaiSyuuekiKei {
            get {
                return ResourceManager.GetString("CaptionServiceKatsudouGaiSyuuekiKei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サービス活動外増減差額 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionServiceKatsudouGaiZougenSagaku {
            get {
                return ResourceManager.GetString("CaptionServiceKatsudouGaiZougenSagaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サービス活動費用計 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionServiceKatsudouHiyouKei {
            get {
                return ResourceManager.GetString("CaptionServiceKatsudouHiyouKei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サービス活動収益計 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionServiceKatsudouSyuuekiKei {
            get {
                return ResourceManager.GetString("CaptionServiceKatsudouSyuuekiKei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サービス活動増減差額 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionServiceKatsudouZougenSagaku {
            get {
                return ResourceManager.GetString("CaptionServiceKatsudouZougenSagaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   施設設備等支出計 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionShisetsuShisyutsuKei {
            get {
                return ResourceManager.GetString("CaptionShisetsuShisyutsuKei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   施設設備等収入計 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionShisetsuSyuunyuuKei {
            get {
                return ResourceManager.GetString("CaptionShisetsuSyuunyuuKei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   施設設備等による収支 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionShisetsuSyuushi {
            get {
                return ResourceManager.GetString("CaptionShisetsuSyuushi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   施設設備等資金収支差額 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionShisetsuSyuushiSagaku {
            get {
                return ResourceManager.GetString("CaptionShisetsuSyuushiSagaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他の固定資産（無形固定資産） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionSonotaKoteishisanMukei {
            get {
                return ResourceManager.GetString("CaptionSonotaKoteishisanMukei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他の固定資産（有形固定資産） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionSonotaKoteishisanYuukei {
            get {
                return ResourceManager.GetString("CaptionSonotaKoteishisanYuukei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他の活動支出計 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionSonotaShisyutsuKei {
            get {
                return ResourceManager.GetString("CaptionSonotaShisyutsuKei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他の活動収入計 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionSonotaSyuunyuuKei {
            get {
                return ResourceManager.GetString("CaptionSonotaSyuunyuuKei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他の活動による収支 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionSonotaSyuushi {
            get {
                return ResourceManager.GetString("CaptionSonotaSyuushi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他の活動資金収支差額 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionSonotaSyuushiSagaku {
            get {
                return ResourceManager.GetString("CaptionSonotaSyuushiSagaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   特別費用計 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionTokubetsuHiyouKei {
            get {
                return ResourceManager.GetString("CaptionTokubetsuHiyouKei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   特別収益計 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionTokubetsuSyuuekiKei {
            get {
                return ResourceManager.GetString("CaptionTokubetsuSyuuekiKei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   特別増減差額 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionTokubetsuZougenSagaku {
            get {
                return ResourceManager.GetString("CaptionTokubetsuZougenSagaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   当期末支払資金残高 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionToukimatsuShiharaiShikinZandaka {
            get {
                return ResourceManager.GetString("CaptionToukimatsuShiharaiShikinZandaka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   当期資金収支差額合計 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionToukiShikinSyuushiSagakuGoukei {
            get {
                return ResourceManager.GetString("CaptionToukiShikinSyuushiSagakuGoukei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   注意 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionWarning {
            get {
                return ResourceManager.GetString("CaptionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予備費支出 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionYobihiShisyutsu {
            get {
                return ResourceManager.GetString("CaptionYobihiShisyutsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   〒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionYuubinMark {
            get {
                return ResourceManager.GetString("CaptionYuubinMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前期末支払資金残高 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptionZenkimatsuShiharaiShikinZandaka {
            get {
                return ResourceManager.GetString("CaptionZenkimatsuShiharaiShikinZandaka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   該当なし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConstantGaitounashi {
            get {
                return ResourceManager.GetString("ConstantGaitounashi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   特記事項なし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConstantTokuhitsujikouNasi {
            get {
                return ResourceManager.GetString("ConstantTokuhitsujikouNasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap create {
            get {
                object obj = ResourceManager.GetObject("create", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap denpyou_grid_header {
            get {
                object obj = ResourceManager.GetObject("denpyou_grid_header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap down_right {
            get {
                object obj = ResourceManager.GetObject("down_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap draw_pencil {
            get {
                object obj = ResourceManager.GetObject("draw_pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   親区分に予算が設定されています。親区分の予算を引き継ぎます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgCheckParentKubunYosan {
            get {
                return ResourceManager.GetString("MsgCheckParentKubunYosan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理が終了しました。必要に応じて変更してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgCompleteCopyYosan {
            get {
                return ResourceManager.GetString("MsgCompleteCopyYosan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在指定されている前年度の予算データを今年度の通常予算としてデータをコピーします。
        ///実行してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgConfirmCopyYosan {
            get {
                return ResourceManager.GetString("MsgConfirmCopyYosan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された情報で予算データを削除します。削除されたデータは元に戻すことができません。
        ///実行してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgConfirmDeleteYosan {
            get {
                return ResourceManager.GetString("MsgConfirmDeleteYosan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   伝票を削除した場合、償却明細の「伝票発行」チェックを解除してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgConfirmSyoukyakuMeisaiDenpyouHakkou {
            get {
                return ResourceManager.GetString("MsgConfirmSyoukyakuMeisaiDenpyouHakkou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除したデータは元に戻すことができません。
        ///本当に削除してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgConfirmToDeleteRow {
            get {
                return ResourceManager.GetString("MsgConfirmToDeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべての伝票のチェックを解除します。解除したものは元に戻せません。実行しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgConfirmUncheckAll {
            get {
                return ResourceManager.GetString("MsgConfirmUncheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前期末支払資金残高を変更します。元に戻すことができません。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgConfirmZenkimatsuShiharaiShikinZandakaChange {
            get {
                return ResourceManager.GetString("MsgConfirmZenkimatsuShiharaiShikinZandakaChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   西暦から和暦への変換に失敗しました。 : %s に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgDate2WarekiConvError {
            get {
                return ResourceManager.GetString("MsgDate2WarekiConvError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データベースのオープンに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgDBOpenError {
            get {
                return ResourceManager.GetString("MsgDBOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   小区分／補助科目を先に全て削除してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgDeleteHojoKamoku {
            get {
                return ResourceManager.GetString("MsgDeleteHojoKamoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   科目コードが重複しています。重複しないように修正してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgDuplicatedKamokuCode {
            get {
                return ResourceManager.GetString("MsgDuplicatedKamokuCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   先頭値のため値を取得できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgFailedToCopyUpperRow {
            get {
                return ResourceManager.GetString("MsgFailedToCopyUpperRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このレコードを削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgFailedToRemoveRow {
            get {
                return ResourceManager.GetString("MsgFailedToRemoveRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力された番号の補助科目は登録されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgHojoSeiriNotFound {
            get {
                return ResourceManager.GetString("MsgHojoSeiriNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この科目は損益伝票で振り替える必要があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgHurikaeTaisyouKamoku {
            get {
                return ResourceManager.GetString("MsgHurikaeTaisyouKamoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %s件のデータを会計伝票に一括登録します。
        ///変更は元に戻せません。一括登録処理を実行しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgIkkatsuTourokuConfirm {
            get {
                return ResourceManager.GetString("MsgIkkatsuTourokuConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一括登録の対象となるデータが０件です。処理を中断します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgIkkatsuTourokuNoDataSelected {
            get {
                return ResourceManager.GetString("MsgIkkatsuTourokuNoDataSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力データが不十分です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgInputDataIncomplete {
            get {
                return ResourceManager.GetString("MsgInputDataIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録が終了しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgInsertSuccess {
            get {
                return ResourceManager.GetString("MsgInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   補助科目の指定が正しくありません。登録されている会計区分と一致しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgInvaidHojoSeiri {
            get {
                return ResourceManager.GetString("MsgInvaidHojoSeiri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された番号の処理はありません。もう一度入力しなおしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgInvalidActivityType {
            get {
                return ResourceManager.GetString("MsgInvalidActivityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付の入力が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgInvalidDate {
            get {
                return ResourceManager.GetString("MsgInvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   伝票番号の入力が不正です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgInvalidDenpyouBangou {
            get {
                return ResourceManager.GetString("MsgInvalidDenpyouBangou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   補助科目の指定が正しくありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgInvalidHojoKamoku {
            get {
                return ResourceManager.GetString("MsgInvalidHojoKamoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   補正予算の登録の時には何回目の補正予算か入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgInvalidHoseiKaisuu {
            get {
                return ResourceManager.GetString("MsgInvalidHoseiKaisuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   補正回数の入力が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgInvalidHoseiKaisuuInput {
            get {
                return ResourceManager.GetString("MsgInvalidHoseiKaisuuInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正な入力です。 : %s に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgInvalidInput {
            get {
                return ResourceManager.GetString("MsgInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会計区分の値が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgInvalidKaikeiKubun {
            get {
                return ResourceManager.GetString("MsgInvalidKaikeiKubun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   科目の指定が正しくありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgInvalidKamoku {
            get {
                return ResourceManager.GetString("MsgInvalidKamoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   借方科目コードの指定が正しくありません。科目コードは５桁で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgInvalidKarikataKamokuCode {
            get {
                return ResourceManager.GetString("MsgInvalidKarikataKamokuCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   貸方科目コードの指定が正しくありません。科目コードは５桁で入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgInvalidKashikataKamokuCode {
            get {
                return ResourceManager.GetString("MsgInvalidKashikataKamokuCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   年度の入力が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgInvalidYear {
            get {
                return ResourceManager.GetString("MsgInvalidYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予算区分の値が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgInvalidYosanKubun {
            get {
                return ResourceManager.GetString("MsgInvalidYosanKubun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会計区分が選択されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgKaikeiKubunNotSelected {
            get {
                return ResourceManager.GetString("MsgKaikeiKubunNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このレコードは決算済みのため編集できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgKessanSyuuryou {
            get {
                return ResourceManager.GetString("MsgKessanSyuuryou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録された起票日は現在の年度の範囲にありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgKihyoubiOutOfRange {
            get {
                return ResourceManager.GetString("MsgKihyoubiOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された年度のデータは存在しません。
        ///処理を中断します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgKurikoshiZumiDataNotFount {
            get {
                return ResourceManager.GetString("MsgKurikoshiZumiDataNotFount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライセンス認証された有効期限を越えてシステムを使用することはできません。
        ///システムを強制終了します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgLicenseError {
            get {
                return ResourceManager.GetString("MsgLicenseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この借方科目には補助科目が登録されています。
        ///借方補助科目を指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgNoKarikataHojoSeiri {
            get {
                return ResourceManager.GetString("MsgNoKarikataHojoSeiri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   借方科目が指定されていません。科目を指定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgNoKarikataKamokuCode {
            get {
                return ResourceManager.GetString("MsgNoKarikataKamokuCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この貸方科目には補助科目が登録されています。
        ///貸方補助科目を指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgNoKashikataHojoSeiri {
            get {
                return ResourceManager.GetString("MsgNoKashikataHojoSeiri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   貸方科目が指定されていません。科目を指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgNoKashikataKamokuCode {
            get {
                return ResourceManager.GetString("MsgNoKashikataKamokuCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgNotExist {
            get {
                return ResourceManager.GetString("MsgNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷対象が選択されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgPrintTargetIsNotSelected {
            get {
                return ResourceManager.GetString("MsgPrintTargetIsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索が終了しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgSearchSuccess {
            get {
                return ResourceManager.GetString("MsgSearchSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この科目は勘定科目マスタで使用しない設定になっています。
        ///別の科目コードを入力するか勘定科目マスタの設定を見直してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgShiyouKubun {
            get {
                return ResourceManager.GetString("MsgShiyouKubun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理が終了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgSucceeded {
            get {
                return ResourceManager.GetString("MsgSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取引区分が選択されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgTorihikiKubunNotSelected {
            get {
                return ResourceManager.GetString("MsgTorihikiKubunNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この科目は会計伝票で使用されているため削除できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgUsedKamokuCanNotDelete {
            get {
                return ResourceManager.GetString("MsgUsedKamokuCanNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この摘要は会計伝票で使用されているので削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgUsedTekiyouCanntRemove {
            get {
                return ResourceManager.GetString("MsgUsedTekiyouCanntRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %s年度の繰越済みデータを使用しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgUseKurikoshiZumiData {
            get {
                return ResourceManager.GetString("MsgUseKurikoshiZumiData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定した年度に登録済みのデータがありました。大区分データのコピーを省略します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgYosanDaikubunAlreadyExist {
            get {
                return ResourceManager.GetString("MsgYosanDaikubunAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された条件の予算は入力がありません。
        ///新規登録を行ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgYosanDataIsNotExist {
            get {
                return ResourceManager.GetString("MsgYosanDataIsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定した年度に登録済みのデータがありました。補助科目データのコピーを省略します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgYosanHojoKamokuAlreadyExist {
            get {
                return ResourceManager.GetString("MsgYosanHojoKamokuAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定した年度に登録済みのデータがありました。科目データのコピーを省略します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgYosanKamokuAlreadyExist {
            get {
                return ResourceManager.GetString("MsgYosanKamokuAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定した年度に登録済みのデータがありました。予備費データのコピーを省略します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgYosanYobihiAlreadyExist {
            get {
                return ResourceManager.GetString("MsgYosanYobihiAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメントを入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusComment {
            get {
                return ResourceManager.GetString("StatusComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示するデータ区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusDataTypeSelection {
            get {
                return ResourceManager.GetString("StatusDataTypeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日を入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusDay {
            get {
                return ResourceManager.GetString("StatusDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認用チェックボックス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusDenpyouKakunin {
            get {
                return ResourceManager.GetString("StatusDenpyouKakunin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   伝票整理番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusDenpyouSeiriBangou {
            get {
                return ResourceManager.GetString("StatusDenpyouSeiriBangou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   元号を入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusGengou {
            get {
                return ResourceManager.GetString("StatusGengou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   補助科目コードを入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusHojoSeiri {
            get {
                return ResourceManager.GetString("StatusHojoSeiri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会計区分を入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusKaikeiKubun {
            get {
                return ResourceManager.GetString("StatusKaikeiKubun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   借方勘定科目コードを入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusKarikataKamokuCode {
            get {
                return ResourceManager.GetString("StatusKarikataKamokuCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   貸方勘定科目コードを入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusKashikataKamokuCode {
            get {
                return ResourceManager.GetString("StatusKashikataKamokuCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   経理区分を入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusKeiriKubun {
            get {
                return ResourceManager.GetString("StatusKeiriKubun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   金額を入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusKingaku {
            get {
                return ResourceManager.GetString("StatusKingaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月を入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusMonth {
            get {
                return ResourceManager.GetString("StatusMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規レコードに移動します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusMoveToNewRow {
            get {
                return ResourceManager.GetString("StatusMoveToNewRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メニューに戻ります に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusReturnToMenu {
            get {
                return ResourceManager.GetString("StatusReturnToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象補助科目を選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusSelectHojoKamoku {
            get {
                return ResourceManager.GetString("StatusSelectHojoKamoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会計区分を選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusSelectKaikeiKubun {
            get {
                return ResourceManager.GetString("StatusSelectKaikeiKubun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象科目を選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusSelectKamoku {
            get {
                return ResourceManager.GetString("StatusSelectKamoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   経理区分を選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusSelectKeiriKubun {
            get {
                return ResourceManager.GetString("StatusSelectKeiriKubun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   記載されている会計伝票を開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusShowDenpyouInfo {
            get {
                return ResourceManager.GetString("StatusShowDenpyouInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択された年月・科目の補助元帳表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusShowHojoMototyou {
            get {
                return ResourceManager.GetString("StatusShowHojoMototyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正な入力の伝票を確認します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusShowInvalidRow {
            get {
                return ResourceManager.GetString("StatusShowInvalidRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   勘定科目を表示します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusShowKamokuPopup {
            get {
                return ResourceManager.GetString("StatusShowKamokuPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択された年月・科目で元帳表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusShowMototyou {
            get {
                return ResourceManager.GetString("StatusShowMototyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   摘要を表示します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusShowTekiyouPopup {
            get {
                return ResourceManager.GetString("StatusShowTekiyouPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   補助機能を使います に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusSubfunction {
            get {
                return ResourceManager.GetString("StatusSubfunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   摘要コードを入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusTekiyou {
            get {
                return ResourceManager.GetString("StatusTekiyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取引区分を入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusTorihikiKubun {
            get {
                return ResourceManager.GetString("StatusTorihikiKubun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   年を入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusYear {
            get {
                return ResourceManager.GetString("StatusYear", resourceCulture);
            }
        }
    }
}
